/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sort.h"

bool_t
xdr_datain (XDR *xdrs, datain *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (3 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->data, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->option))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->key))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->data;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->size);
			IXDR_PUT_LONG(buf, objp->option);
			IXDR_PUT_LONG(buf, objp->key);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (3 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->data, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->option))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->key))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->data;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->size = IXDR_GET_LONG(buf);
			objp->option = IXDR_GET_LONG(buf);
			objp->key = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->data, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->option))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dataout (XDR *xdrs, dataout *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (3 +  500 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->result, 500,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->result_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->index_search))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->delete_status))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->result;
					i < 500; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->result_size);
			IXDR_PUT_LONG(buf, objp->index_search);
			IXDR_PUT_LONG(buf, objp->delete_status);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (3 +  500 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->result, 500,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->result_size))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->index_search))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->delete_status))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->result;
					i < 500; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->result_size = IXDR_GET_LONG(buf);
			objp->index_search = IXDR_GET_LONG(buf);
			objp->delete_status = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->result, 500,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result_size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index_search))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->delete_status))
		 return FALSE;
	return TRUE;
}
