/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct datain {
	int data[100];
	int size;
	int option;
	int key;
};
typedef struct datain datain;

struct dataout {
	int result[500];
	int result_size;
	int index_search;
	int delete_status;
};
typedef struct dataout dataout;

#define SORTING 0x23451111
#define SORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SORT 1
extern  dataout * sort_1(datain *, CLIENT *);
extern  dataout * sort_1_svc(datain *, struct svc_req *);
extern int sorting_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SORT 1
extern  dataout * sort_1();
extern  dataout * sort_1_svc();
extern int sorting_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datain (XDR *, datain*);
extern  bool_t xdr_dataout (XDR *, dataout*);

#else /* K&R C */
extern bool_t xdr_datain ();
extern bool_t xdr_dataout ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
